

export const list_intro_shell = [



													["Network state","L’état de réseau désigne la situation actuelle et dynamique d’un réseau, incluant la disponibilité des nœuds, la configuration des connexions, la topologie active, le trafic en cours, les routes valides, ainsi que les pannes ou congestions éventuelles affectant la communication."],
													[" virtual circuit","Un circuit virtuel est une connexion logique établie entre deux points dans un réseau qui simule un chemin dédié, garantissant l'ordre et la fiabilité des paquets transmis, sans nécessiter de liaison physique permanente entre eux"],
													["signaling","La signalisation en réseaux désigne l'ensemble des échanges de messages de contrôle entre équipements pour établir, gérer, modifier et terminer une communication ou une connexion, sans transmettre les données utilisateur elles-mêmes."],
													["digital network","Un réseau numérique est un système de communication où les informations (voix, données, vidéo) sont transmises sous forme de signaux numériques codés, assurant une meilleure qualité, sécurité et compatibilité avec les technologies modernes"],
													["switching network","Un réseau de transfert est une infrastructure qui permet l’acheminement et la commutation des données entre plusieurs points d’un réseau, assurant la transmission efficace des paquets ou circuits"],
													["switching node","Un nœud de transfert est un équipement réseau (comme un routeur ou un commutateur) chargé de recevoir, traiter et retransmettre les données vers leur prochaine destination dans un réseau"],
													["packetization","La paquétisation est le processus de découpage des données en unités appelées paquets pour leur transmission sur un réseau"],
													["reassembly","Le contraire de la paquétisation est le réassemblage, processus qui consiste à reconstituer les données initiales à partir des paquets reçus"],
													["remote terminals","Les terminaux distants sont des équipements utilisateurs connectés à un réseau depuis un emplacement éloigné pour accéder aux services ou ressources"],
													["Local Area Network.","LAN : Réseau local qui connecte des appareils sur une zone géographique limitée comme un bâtiment ou un bureau, permettant le partage de ressources"],
													["Metropolitan Area Network","Réseau métropolitain couvrant une ville ou une zone urbaine étendue pour interconnecter plusieurs LAN"],
													["Wide Area Network"," Réseau étendu qui relie des réseaux locaux sur de grandes distances géographiques, souvent via des liaisons publiques ou privées"],
													["Radio Access Network","Réseau d’accès radio qui connecte les utilisateurs mobiles à un réseau filaire via des technologies sans fil"],
													["isochronous communication","Communication isochrone : Mode de communication où les données sont transmises à intervalles réguliers et constants, garantissant un débit temporel stable mais sans stricte synchronisation bit à bit, souvent utilisé pour les flux multimédias temps réel afin de préserver la continuité"],											
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],									
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
													[],
						



]
