

export const maths_list = [

				["erreurs d’arrondi",],
				["erreurs sur les données",],
				["erreurs de troncature",],
				["erreur absolue",],
				["erreur relative",],
				["mise à l’échelle",],
				["algorithme est dit séquentiel",],
				["algorithme est dit parallèle",],
				["algorithme est dit distribué",],
				["La programmation dynamique",],
				["complexité temporelle",],
				["complexité spatiale",],
				["application f","est un procédé qui associe à toutélément a de A un unique élément f (a) de B"],
				["racine","n nombre a est racine d’un polynôme P si et seulement s’il existe unpolynôme Q tel que P = (X − a)Q."],
				["Multiplicité des racines","Une racine a d’un polynôme P est de multiplicité k si P s’écrit son la forme P = (X − a)kQ mais pas sous la forme (X − a)k+1R"],
				["théorème fondamentale de l'algèbre ","Tout polynome de degré n >=1 à coefficients complexes admet exactement n racines complexes, comptées avec multiplicité."],
				["loi de composition interne : ", "opération qui à partir de deux éléments d'un ensemble donné produit un élément qui appartient au meme ensemble"],
				["l'algèbre abstraite ","branche dees mathématiques qui étudie des structures algébriques générales comme les groupes, anneaux, corps, espaces vectoriels, modules ..."],
				["structure algébrique","ensemble muni d'une ou plusieurs oérations qui respectent certaines règles (axiomes)"],
				["U+V :","U + V := {~u + ~v | ~u ∈ U, ~v ∈ V }"],
				["théorie de l'information","sans précision, est le nom usuel désignant la théorie de l'information de Shannon, qui est une théorie utilisant les probabilités pour quantifier le contenu moyen en information d'un ensemble de messages, dont le codage informatique satisfait une distribution statistique que l'on pense connaître"],
				["addivité de f","f(u+v)=f(u)°f(v)"],
				["homogénéité de f","f(a.u)=a.f(a)"],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				
				
]
