

export const osi_list = [
													



				["Network state","L’état de réseau désigne la situation actuelle et dynamique d’un réseau, incluant la disponibilité des nœuds, la configuration des connexions, la topologie active, le trafic en cours, les routes valides, ainsi que les pannes ou congestions éventuelles affectant la communication."],
				[" virtual circuit","Un circuit virtuel est une connexion logique établie entre deux points dans un réseau qui simule un chemin dédié, garantissant l'ordre et la fiabilité des paquets transmis, sans nécessiter de liaison physique permanente entre eux"],
				["signaling","La signalisation en réseaux désigne l'ensemble des échanges de messages de contrôle entre équipements pour établir, gérer, modifier et terminer une communication ou une connexion, sans transmettre les données utilisateur elles-mêmes."],
				["digital network","Un réseau numérique est un système de communication où les informations (voix, données, vidéo) sont transmises sous forme de signaux numériques codés, assurant une meilleure qualité, sécurité et compatibilité avec les technologies modernes"],
				["switching network","Un réseau de transfert est une infrastructure qui permet l’acheminement et la commutation des données entre plusieurs points d’un réseau, assurant la transmission efficace des paquets ou circuits"],
				["switching node","Un nœud de transfert est un équipement réseau (comme un routeur ou un commutateur) chargé de recevoir, traiter et retransmettre les données vers leur prochaine destination dans un réseau"],
				["packetization","La paquétisation est le processus de découpage des données en unités appelées paquets pour leur transmission sur un réseau"],
				["reassembly","Le contraire de la paquétisation est le réassemblage, processus qui consiste à reconstituer les données initiales à partir des paquets reçus"],
				["remote terminals","Les terminaux distants sont des équipements utilisateurs connectés à un réseau depuis un emplacement éloigné pour accéder aux services ou ressources"],
				["Local Area Network.","LAN : Réseau local qui connecte des appareils sur une zone géographique limitée comme un bâtiment ou un bureau, permettant le partage de ressources"],
				["Metropolitan Area Network","Réseau métropolitain couvrant une ville ou une zone urbaine étendue pour interconnecter plusieurs LAN"],
				["Wide Area Network"," Réseau étendu qui relie des réseaux locaux sur de grandes distances géographiques, souvent via des liaisons publiques ou privées"],
				["Radio Access Network","Réseau d’accès radio qui connecte les utilisateurs mobiles à un réseau filaire via des technologies sans fil"],
				["isochronous communication","Communication isochrone : Mode de communication où les données sont transmises à intervalles réguliers et constants, garantissant un débit temporel stable mais sans stricte synchronisation bit à bit, souvent utilisé pour les flux multimédias temps réel afin de préserver la continuité"],											
				["wired network","Un réseau câblé est un réseau de communication utilisant des supports physiques comme le cuivre (paires torsadées), le coaxial ou la fibre optique pour transmettre les données, offrant généralement une grande stabilité et une haute bande passante"],
				["wireless network","Un réseau hertzien est un réseau de communication utilisant des ondes radio ou micro-ondes pour transmettre des données sans support physique direct, ce qui inclut le Wi-Fi, la 4G/5G et les liaisons satellites"],
				[" digital channel","Un canal numérique est un chemin de transmission permettant de transporter des informations codées sous forme binaire entre deux points d’un réseau en utilisant des techniques de multiplexage et de synchronisation pour assurer l’intégrité des données"],
				["switching table","Une table de commutation est une structure interne d’un commutateur réseau qui associe les adresses MAC aux ports physiques pour acheminer efficacement les trames vers leur destination correcte dans un réseau local"],
				["switch","Un commutateur est un équipement réseau de la couche 2 qui connecte plusieurs appareils dans un LAN en utilisant les adresses MAC pour transmettre les trames uniquement au port destinataire, améliorant ainsi la performance et la sécurité du réseau"],
				["shared memory architecture","Architecture mémoire partagée : Modèle d’architecture informatique où plusieurs processeurs accèdent simultanément à une même mémoire centrale partagée pour communiquer et synchroniser leurs opérations, ce qui facilite l’échange rapide de données mais nécessite des mécanismes de gestion des accès concurrents"],
				["shared memory switching architecture","Dans le contexte réseau et commutateur, l’architecture mémoire partagée est une conception interne où toutes les interfaces du commutateur accèdent à une mémoire tampon commune pour stocker temporairement les trames avant leur transmission, ce qui permet une allocation dynamique de la mémoire entre les ports et améliore l’efficacité par rapport à une architecture à mémoires séparées"],
				["distributed memory switching architecture","Dans le contexte réseau et commutateur, l’architecture mémoire distribuée est une conception où chaque port du commutateur possède sa propre mémoire tampon pour stocker les trames reçues avant transmission, ce qui réduit la contention d’accès mais peut entraîner des déséquilibres si certains ports sont saturés"],
				["crossbar switching architecture","Dans le contexte des commutateurs réseau, l’architecture crossbar est une structure matérielle en matrice reliant chaque port d’entrée à chaque port de sortie via des chemins de commutation indépendants, permettant des connexions simultanées multiples sans conflit, ce qui améliore les performances en haute capacité"],
				["crosspoint switch","Un crosspoint switch est un composant électronique situé à l’intersection d’une ligne d’entrée et d’une ligne de sortie dans une matrice de commutation (crossbar), qui contrôle l’établissement ou la coupure de la connexion entre ces deux lignes, permettant ainsi la configuration dynamique des chemins à l’intérieur du commutateur"],
				["full duplex","Mode de communication permettant la transmission simultanée et bidirectionnelle des données entre deux équipements sans interruption ni collision"],
				["scheduler","Dans un commutateur, un scheduler est un mécanisme qui planifie l’ordre et le timing de l’envoi des trames sur les ports de sortie afin de gérer efficacement la bande passante, éviter les conflits et garantir la qualité de service"],
				["blocking switching","ode de commutation où certaines connexions peuvent être refusées ou retardées parce que les ressources (comme les voies ou la mémoire) sont insuffisantes pour établir tous les chemins demandés simultanément"],
				["link","Dans un commutateur réseau, une liaison désigne le canal physique ou logique qui connecte un port du commutateur à un autre équipement (ordinateur, serveur, autre commutateur) permettant le transfert de trames entre eux ; cette liaison peut être un câble Ethernet cuivre, une fibre optique ou une connexion sans fil, assurant la communication bidirectionnelle entre les nœuds du réseau."],
				["EtherChannel","EtherChannel : Technologie Cisco permettant d’agréger plusieurs liaisons Ethernet physiques en une seule liaison logique pour augmenter la bande passante et assurer la redondance entre commutateurs ou entre un commutateur et un serveur"],
				["lacp","LACP (Link Aggregation Control Protocol) : Protocole standard IEEE 802.3ad qui permet d’agréger dynamiquement plusieurs liens physiques Ethernet en un seul lien logique pour augmenter la bande passante et fournir de la redondance entre équipements réseau"],
				["backbone réseau","Un backbone réseau est l’infrastructure principale d’un réseau, composée de liens à très haut débit et d’équipements de commutation ou de routage, qui interconnecte les différents sous-réseaux ou segments pour assurer un acheminement rapide et fiable des données à grande échelle, correspondance anglaise : network backbone."],
				["uplink","Un uplink est une liaison réseau reliant un commutateur ou un périphérique réseau à un équipement de niveau supérieur, comme un routeur, un autre commutateur ou un backbone, afin d’acheminer le trafic vers un réseau plus large ou vers Internet"],
				["access switch","Un switch d’accès est un commutateur situé à la périphérie d’un réseau (couche d’accès dans une architecture hiérarchique) qui connecte directement les périphériques finaux tels que PC, imprimantes, téléphones IP au réseau local, en fournissant des services comme la commutation Ethernet, le VLAN et parfois l’alimentation PoE"],
				["distribution switch","Un switch de distribution est un commutateur intermédiaire situé entre les switches d’accès et le cœur de réseau, chargé d’agréger le trafic provenant de plusieurs switches d’accès, d’appliquer des politiques réseau comme la sécurité, la qualité de service (QoS) et le routage inter-VLAN, assurant ainsi la connexion efficace entre la couche d’accès et la couche cœur"],
				["core switches","Les switches cœur sont des commutateurs haute performance situés au niveau central d’une architecture réseau en couches, responsables de l’acheminement rapide et fiable du trafic entre les différentes parties du réseau, en assurant une haute disponibilité, une redondance et une faible latence pour supporter les échanges entre switches de distribution et autres segments"],
				["Virtual LAN Link","Lien qui connecte plusieurs switches pour transporter le trafic de plusieurs VLANs simultanément en utilisant un protocole de balisage comme 802.1Q afin de maintenir la séparation des VLANs sur ce lien."],
				["Point-to-Point Link","Connexion directe entre deux équipements réseau permettant une communication exclusive et dédiée sans intermédiaire ni partage de bande passante avec d’autres dispositifs."],
				["Store-and-Forward","Méthode de commutation où le commutateur reçoit une trame complète, vérifie son intégrité via le CRC, puis la retransmet au port de sortie, offrant une fiabilité accrue mais avec une légère latence."],
				["Cut-Through","Méthode de commutation où le commutateur commence à transmettre une trame dès la lecture de l’adresse MAC de destination sans attendre la réception complète, ce qui réduit la latence mais n’effectue pas de vérification d’erreurs complète."],
				["Fragment-Free","Méthode de commutation où le commutateur attend de recevoir les 64 premiers octets de la trame avant de commencer la transmission, afin de filtrer les trames corrompues dues aux collisions tout en réduisant la latence par rapport au store-and-forward."],
				[" mémoire tampon (buffer) dans un switch","Zone de stockage temporaire dans un commutateur réseau utilisée pour conserver les trames reçues avant leur traitement ou leur transmission afin de gérer les variations de trafic et éviter la perte de données."],
				["Buffered Switching","Technique de commutation où les trames sont stockées dans une mémoire tampon avant d’être transmises pour gérer la congestion et améliorer la fluidité du trafic dans le commutateur."],
				["interface physique (PHY) ","Composant matériel d’un commutateur responsable de la transmission et de la réception des signaux électriques ou optiques sur le support physique, assurant la conversion entre les données numériques et les signaux adaptés au média de communication"],
				["etape d'un switch ","Réception ➡ Vérification ➡ Apprentissage MAC ➡ Recherche MAC ➡ Décision ➡ Mise en file ➡ Transmission"],
				["spatial allocation","Méthode utilisée dans un commutateur pour organiser et distribuer les ressources internes, comme la mémoire tampon et les files d’attente, entre différents ports afin d’optimiser l’utilisation des capacités physiques et éviter la saturation locale"],
				["time division","Technique consistant à planifier l’accès aux ressources de commutation selon des intervalles temporels pour chaque flux ou port, garantissant une alternance équitable et évitant la congestion en assurant un partage ordonné des capacités."],
				["Flow Control","Le contrôle de flux est un mécanisme utilisé pour réguler le trafic entre deux équipements réseau afin d’éviter la perte de données due à une saturation temporaire."],
				["Congestion Control","Le contrôle de congestion est un ensemble de mécanismes utilisés pour éviter ou gérer la surcharge d’un réseau, c’est-à-dire lorsque la quantité de trafic dépasse la capacité du réseau à le traiter."],
				["Blocking","Le blocage désigne une situation dans un switch ou un réseau où un ou plusieurs paquets ne peuvent pas être transmis immédiatement parce que la ressource nécessaire (port de sortie, mémoire tampon, chemin interne) est occupée ou saturée."],
				["switching fabric","Un nœud de commutation (en anglais : switching fabric, est le cœur matériel interne d’un commutateur ou routeur qui assure le transfert des paquets ou trames d’une interface d’entrée à une interface de sortie."],
				["puce ASIC","Une puce ASIC est une puce électronique conçue sur mesure pour exécuter une tâche très précise, à très haute vitesse, et de façon très efficace."],
				["flot","Un flot désigne un ensemble de paquets qui partagent des caractéristiques communes et sont traités comme un tout pendant leur transmission"],
				["commutation","La commutation est une méthode utilisée dans les réseaux pour transférer les données d’un point à un autre en choisissant dynamiquement le chemin à travers un équipement de commutation (ex : un switch, un routeur, un commutateur téléphonique, etc.)."],
				["Commutation Ethernet","La commutation Ethernet est le processus par lequel un switch Ethernet transfère des trames Ethernet d’un port à un autre en fonction de l’adresse MAC de destination."],
				["objet","entité ou une donnée représentée ou manipulée par une couche, souvent abstraite, et qui sert d'interface ou d’unité de communication entre deux entités au même niveau."],
				["service d'une couche","Un service d'une couche est un ensemble d'opérations (comme envoyer ou recevoir des données) qu'une couche met à disposition de la couche immédiatement supérieure."],									
				["N-SAP ","interface par lequel une couche n+1 accède au service que lui propose la couche n "],
				["sémantique d’association","Selon l'iso 7498 La sémantique d’association est la définition des modalités de communication entre deux entités homologues d’une couche donnée. Elle décrit comment ces entités vont dialoguer, échanger des données et se coordonner."],
				["entité de service","Dans le modèle OSI, une entité de service (ou service entity) est une partie fonctionnelle d'une couche qui fournit un service spécifique à la couche immédiatement supérieure."],
				["NSAP Address","adresse logique utilisée dans le modèle OSI pour identifier précisément un point d’accès au service de la couche réseau."],
				[""],
				["Connection Establishment","La procédure par laquelle deux entités communicantes initient une association afin de commencer la communication. Cela inclut la négociation des paramètres et l’autorisation de la connexion."],
				["Data Transfer","Durant cette phase, les entités réalisent l’échange des unités de données conformément aux règles établies lors de l’établissement."],
				["Connection Release","Phase de terminaison de la communication, où les entités se quittent proprement pour éviter toute perte de données."],
				["Connection Type","Spécifie si la communication est réalisée en mode avec connexion (connection-oriented) ou sans connexion (connectionless)."],
				["Sémantique de fonctionnalité","spécifie les fonctions de communication offertes par une entité de couche N à son entité homologue distante (dans le système distant), en se basant sur les règles du protocole de cette couche. Elle définit donc le rôle fonctionnel du protocole dans la mise en œuvre du service."],
				["Service primitives","Ce sont des opérations élémentaires utilisées par une entité de couche pour demander un service à la couche immédiatement inférieure ou pour informer la couche immédiatement supérieure d’un événement.Elles servent à formaliser les échanges entre couches adjacentes dans une architecture en couches."],
				["	Échange de primitives de service","Correspond à l’ensemble des interactions entre deux entités homologues de même couche, réalisées via leurs couches inférieures respectives, au travers de l’envoi et de la réception de ces primitives.la mise en œuvre du service offert par la couche inférieure à la couche supérieure."],
				["REQUEST",": émise par une entité d’une couche N pour demander un service à la couche (N–1)."],
				["INDICATION","transmise de la couche (N–1) vers la couche N pour informer qu’un événement a eu lieu (souvent côté récepteur)"],
				["RESPONSE","émise par une entité N en réponse à une INDICATION, pour accepter ou rejeter un événement (par exemple, une demande de connexion)."],
				["CONFIRM","transmise par la couche (N–1) vers la couche N pour confirmer qu'une action demandée par REQUEST a été réalisée."],
				["pdu","Un PDU est une unité de données utilisée par une couche spécifique du modèle OSI pour communiquer avec sa couche homologue (la même couche) sur un autre système."],
				["ASN"," Abstract Syntax Notation One, est un standard international pour décrire, représenter et encoder des données de façon indépendante de la machine et du langage"],
				["Bipoint","désigne une communication directe entre deux entités seulement, sans intermédiaires ou diffusion à plusieurs."],
				["m-sdu","C’est le bloc de données qu’une couche N+1 transmet à la couche N pour qu’elle lui fournisse son service."],
				["N-PCI ","C’est l’ensemble des informations de contrôle que la couche N ajoute aux données reçues de la couche N+1 (la N-SDU) pour former le PDU (Protocol Data Unit) à transmettre à la couche inférieure."],
				["IDU","C’est l’ensemble des informations (données + contrôle) échangées à l’interface entre deux couches adjacentes"],
				["connexion N ","ssociation établie pour permettre la communication entre aumoins deux entités N + 1 identifiées par leur adresse N"],
				["Multiplexage"," Le multiplexage est une technique qui permet de faire passer plusieurs flux de données indépendants (plusieurs connexions ou sessions) simultanément sur un même support physique ou logique."],
				["éclatement","une seule connexion ou flux à un niveau supérieur est divisé en plusieurs connexions ou flux au niveau inférieur"],
				["couche physique","Le niveau physique correspond aux règles et procédures à mettre en œuvre pour acheminer les éléments binaires sur le médium physiqu"],
				["niveau trame",". Sa première fonction est de reconnaître, lors de l’arrivée des éléments binaires, les débuts et fins de tram"],
				["architecture cross-layer","Une architecture cross-layer (ou architecture croisée entre couches) est une architecture réseau dans laquelle les différentes couches du modèle OSI ou TCP/IP peuvent interagir directement entre elles, en contournant le cloisonnement classique."],
				["Cat3","âble à paires torsadées non blindées (UTP) supportant une bande passante jusqu’à 16 MHz. Utilisé pour Ethernet 10BaseT (10 Mbps) et téléphonie."],
				["Cat4","Câble UTP supportant une bande passante jusqu’à 20 MHz. Utilisé pour Ethernet 10BaseT (10 Mbps) et réseaux Token-Ring à 16 Mbps"],
				["Cat5","Câble UTP supportant une bande passante jusqu’à 100 MHz. Supporte Ethernet 10BaseT, Token-Ring 16 Mbps, et Fast Ethernet 100BaseTX (100 Mbps)."],
				["Cat5e","Version améliorée du Cat5 avec des spécifications renforcées contre la diaphonie et le bruit. Supporte une bande passante de 100 MHz et Ethernet Gigabit (1 Gbps)."],
				["Cat6","Câble UTP ou blindé supportant une bande passante jusqu’à 200 MHz. Supporte Ethernet Gigabit sur 100 m et 10 Gigabit Ethernet sur 55 m."],
				["Cat7","Câble blindé (STP ou S/FTP) supportant une bande passante jusqu’à 600 MHz. Supporte Ethernet 10 Gigabit sur 100 m avec meilleure protection contre les interférences."],
				["diaphonie "," La diaphonie (ou crosstalk en anglais) est un phénomène en électronique et en télécommunications où un signal transmis sur un câble ou un circuit interfère indésirablement avec un autre signal proche, provoquant une perturbation."],
				["UTP","Les fils sont torsadés par paires pour réduire les interférences électromagnétiques, mais ils ne sont pas blindés."],
				["STP","Chaque paire de fils est entourée d’un blindage métallique, ce qui protège mieux contre les interférences électromagnétiques."],
				["FTP","Toutes les paires torsadées sont entourées d’un seul blindage en feuille (foil), protégeant globalement le câble.	"],
				["S/FTP","Chaque paire est blindée individuellement (foil) et il y a aussi un blindage global tressé autour de toutes les paires."],
				/*[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				[""],
				*/
				



]
